-- ==============================================================================
-- 📊 SQL PORTFOLIO: 50 SOLVED BUSINESS QUESTIONS & INSIGHTS
-- Graded from Easy to Advanced (PostgreSQL / ANSI SQL Syntax)
-- Database Target: E-Commerce Superstore / Subscription / HR Tables
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 🎯 PART 1: BASIC RETRIEVAL & AGGREGATIONS (QUERIES 1-10)
-- ------------------------------------------------------------------------------

-- Q1: What is the total revenue and net profit generated by the business?
-- SQL:
SELECT 
    ROUND(SUM(sales)::numeric, 2) AS total_revenue,
    ROUND(SUM(profit)::numeric, 2) AS total_profit
FROM sales;
-- Insight: Establishes the business baseline. Net profit is critical to evaluate if top-line revenue growth translates to actual earnings.

-- Q2: Find the total number of unique orders and unique customers.
-- SQL:
SELECT 
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers
FROM sales;
-- Insight: Helps evaluate customer frequency. If order count is much higher than customer count, customer loyalty and repeat purchases are strong.

-- Q3: List the unique ship modes available and how many orders used each.
-- SQL:
SELECT 
    ship_mode,
    COUNT(DISTINCT order_id) AS order_count
FROM sales
GROUP BY ship_mode
ORDER BY order_count DESC;
-- Insight: Identifies customer shipping preferences. Standard Class is typically the most popular due to cost efficiency.

-- Q4: What is the average order value (AOV)?
-- SQL:
WITH order_totals AS (
    SELECT order_id, SUM(sales) AS order_sales
    FROM sales
    GROUP BY order_id
)
SELECT ROUND(AVG(order_sales)::numeric, 2) AS average_order_value
FROM order_totals;
-- Insight: Crucial marketing KPI. A higher AOV means customers are buying more expensive items or bundle packs.

-- Q5: Which product categories are sold and what is their average discount?
-- SQL:
SELECT 
    p.category,
    ROUND(AVG(s.discount)::numeric * 100, 2) AS avg_discount_percent
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY avg_discount_percent DESC;
-- Insight: Monitors promotional impact. High discounts eat into profit margins, so this must be cross-referenced with segment profitability.

-- Q6: Which year generated the highest revenue?
-- SQL:
SELECT 
    EXTRACT(YEAR FROM order_date::date) AS sales_year,
    ROUND(SUM(sales)::numeric, 2) AS yearly_revenue
FROM sales
GROUP BY sales_year
ORDER BY yearly_revenue DESC;
-- Insight: Shows high-level annual business growth or contraction trends.

-- Q7: Find the top 5 states by total revenue.
-- SQL:
SELECT 
    c.state,
    ROUND(SUM(s.sales)::numeric, 2) AS total_revenue
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
GROUP BY c.state
ORDER BY total_revenue DESC
LIMIT 5;
-- Insight: Identifies geographic strongholds. Marketing campaigns should focus budget allocations on these high-converting regions.

-- Q8: Find the number of active customers in each segment.
-- SQL:
SELECT 
    segment,
    COUNT(DISTINCT customer_id) AS customer_count
FROM customers
GROUP BY segment
ORDER BY customer_count DESC;
-- Insight: Identifies the customer makeup of the business. Typically, the Consumer segment is the largest driver of volume.

-- Q9: List the total quantity sold for each product category.
-- SQL:
SELECT 
    p.category,
    SUM(s.quantity) AS total_qty
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_qty DESC;
-- Insight: Useful for warehouse logistics and stock replenishment forecasting.

-- Q10: Find all orders where the profit was negative (losses).
-- SQL:
SELECT 
    order_id,
    ROUND(SUM(profit)::numeric, 2) AS net_loss
FROM sales
GROUP BY order_id
HAVING SUM(profit) < 0
ORDER BY net_loss ASC
LIMIT 10;
-- Insight: Pinpoints order transactions that actively drained company cash due to returns, high shipping costs, or heavy discounts.

-- ------------------------------------------------------------------------------
-- 🎯 PART 2: JOINS & SUBQUERIES (QUERIES 11-20)
-- ------------------------------------------------------------------------------

-- Q11: Retrieve order details including customer name, product name, and sales amount.
-- SQL:
SELECT 
    s.order_id,
    c.customer_name,
    p.product_name,
    s.sales
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
JOIN products p ON s.product_id = p.product_id
LIMIT 5;
-- Insight: Standard detail report showing transactional connections.

-- Q12: Which customers have never placed an order? (Assumes customer directory has all registered users).
-- SQL:
SELECT c.customer_id, c.customer_name
FROM customers c
LEFT JOIN sales s ON c.customer_id = s.customer_id
WHERE s.order_line IS NULL;
-- Insight: Re-engagement list for marketing campaigns to target registered users who have not yet purchased.

-- Q13: Find products that have been ordered more than 50 times in total.
-- SQL:
SELECT 
    p.product_id,
    p.product_name,
    COUNT(s.order_line) AS times_ordered
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.product_id, p.product_name
HAVING COUNT(s.order_line) > 50
ORDER BY times_ordered DESC;
-- Insight: Highlights key high-frequency products. These should always be kept in stock.

-- Q14: Find the total revenue from customers who are older than 50.
-- SQL:
SELECT 
    ROUND(SUM(s.sales)::numeric, 2) AS senior_revenue
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
WHERE c.age > 50;
-- Insight: Helps target demographic groups. Verifies the purchasing power of the senior consumer segment.

-- Q15: Which states have store coordinates mapped? (Using Left/Inner Join comparison).
-- SQL:
SELECT 
    sc.state,
    sc.x_coordinate,
    sc.y_coordinate,
    COUNT(c.customer_id) AS customer_density
FROM store_coords sc
LEFT JOIN customers c ON sc.state = c.state
GROUP BY sc.state, sc.x_coordinate, sc.y_coordinate;
-- Insight: Maps exact retail geographic hubs to coordinates, highlighting customer density in CA, TX, and NY.

-- Q16: Find products whose price is above the average sales price across all products.
-- SQL:
SELECT 
    product_id,
    product_name
FROM products
WHERE product_id IN (
    SELECT product_id 
    FROM sales 
    GROUP BY product_id 
    HAVING AVG(sales) > (SELECT AVG(sales) FROM sales)
);
-- Insight: Isolates premium product segments compared to the baseline catalog average.

-- Q17: List the names of customers who placed orders on '2016-11-08'.
-- SQL:
SELECT DISTINCT c.customer_name
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
WHERE s.order_date = '2016-11-08';
-- Insight: Pinpoints transactional activity for specific campaign dates or holiday events.

-- Q18: Find the category-level profit for the 'Consumer' segment.
-- SQL:
SELECT 
    p.category,
    ROUND(SUM(s.profit)::numeric, 2) AS total_profit
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
JOIN products p ON s.product_id = p.product_id
WHERE c.segment = 'Consumer'
GROUP BY p.category
ORDER BY total_profit DESC;
-- Insight: Helps product managers understand which product lines are successful within the consumer retail demographic.

-- Q19: What is the average shipping delay (Ship Date - Order Date) for each ship mode?
-- SQL:
SELECT 
    ship_mode,
    ROUND(AVG(ship_date::date - order_date::date), 1) AS avg_shipping_days
FROM sales
GROUP BY ship_mode
ORDER BY avg_shipping_days ASC;
-- Insight: Key operational efficiency KPI. Verifies if Next Day and Second Class shipping timelines are meeting their SLA standards.

-- Q20: Find products that have never generated a profit (all sales resulted in net losses).
-- SQL:
SELECT 
    p.product_id,
    p.product_name,
    ROUND(SUM(s.profit)::numeric, 2) AS total_loss
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.product_id, p.product_name
HAVING SUM(s.profit) < 0
ORDER BY total_loss ASC;
-- Insight: Candidates for decommissioning. These products are consistently loss-making.

-- ------------------------------------------------------------------------------
-- 🎯 PART 3: CASE STATEMENTS & DATA SEGMENTATION (QUERIES 21-30)
-- ------------------------------------------------------------------------------

-- Q21: Categorize customers into age groups: 'Under 30', '30-50', and '50+'. Show revenue contributions.
-- SQL:
SELECT 
    CASE 
        WHEN c.age < 30 THEN 'Under 30'
        WHEN c.age BETWEEN 30 AND 50 THEN '30-50'
        ELSE '50+'
    END AS age_group,
    ROUND(SUM(s.sales)::numeric, 2) AS total_revenue
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
GROUP BY age_group
ORDER BY total_revenue DESC;
-- Insight: Guides marketing focus. Demonstrates which age cohort contributes the highest revenue share.

-- Q22: Label orders as 'Large Purchase' (Sales > $500) or 'Standard Purchase' and show count.
-- SQL:
SELECT 
    CASE 
        WHEN sales > 500 THEN 'Large Purchase'
        ELSE 'Standard Purchase'
    END AS purchase_tier,
    COUNT(order_line) AS order_line_count
FROM sales
GROUP BY purchase_tier;
-- Insight: Identifies checkout ticket size distributions to check if transaction volume is driven by bulk orders.

-- Q23: Calculate profit margins and tag as 'High Margin' (Margin > 20%), 'Low Margin' (0-20%), or 'Loss-making'.
-- SQL:
SELECT 
    order_id,
    ROUND(SUM(sales)::numeric, 2) AS revenue,
    ROUND(SUM(profit)::numeric, 2) AS profit,
    CASE 
        WHEN SUM(sales) = 0 THEN 'No Sales'
        WHEN (SUM(profit) / SUM(sales)) > 0.20 THEN 'High Margin'
        WHEN (SUM(profit) / SUM(sales)) BETWEEN 0 AND 0.20 THEN 'Low Margin'
        ELSE 'Loss-making'
    END AS profitability_status
FROM sales
GROUP BY order_id
LIMIT 10;
-- Insight: Categorizes order profitability to find where process optimization is needed.

-- Q24: What is the distribution of shipping delays classified into SLA status?
-- SQL:
SELECT 
    CASE 
        WHEN (ship_date::date - order_date::date) <= 2 THEN 'SLA Met (Fast)'
        WHEN (ship_date::date - order_date::date) BETWEEN 3 AND 5 THEN 'SLA Met (Standard)'
        ELSE 'SLA Breached (Late)'
    END AS shipping_sla_status,
    COUNT(order_id) AS order_count
FROM sales
GROUP BY shipping_sla_status;
-- Insight: Identifies delivery quality bottlenecks. High volumes in late categories indicate logisitical strains.

-- Q25: Show regional sales split dynamically by year.
-- SQL:
SELECT 
    c.region,
    ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM s.order_date::date) = 2014 THEN s.sales ELSE 0 END)::numeric, 2) AS sales_2014,
    ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM s.order_date::date) = 2015 THEN s.sales ELSE 0 END)::numeric, 2) AS sales_2015,
    ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM s.order_date::date) = 2016 THEN s.sales ELSE 0 END)::numeric, 2) AS sales_2016,
    ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM s.order_date::date) = 2017 THEN s.sales ELSE 0 END)::numeric, 2) AS sales_2017
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
GROUP BY c.region;
-- Insight: A dynamic pivot summary table. Enables multi-year regional tracking at a glance.

-- Q26: Flag if an order was placed on a Weekend vs. Weekday.
-- SQL:
SELECT 
    CASE 
        WHEN EXTRACT(ISODOW FROM order_date::date) IN (6, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    ROUND(SUM(sales)::numeric, 2) AS total_sales
FROM sales
GROUP BY day_type;
-- Insight: Decides if weekend discounts or weekday email promotions drive the most transactional value.

-- Q27: Calculate product pricing tiers: 'Low End' (<$50), 'Mid Range' ($50-$200), 'High End' (>$200).
-- SQL:
SELECT 
    CASE 
        WHEN sales / quantity < 50 THEN 'Low End'
        WHEN sales / quantity BETWEEN 50 AND 200 THEN 'Mid Range'
        ELSE 'High End'
    END AS pricing_tier,
    COUNT(DISTINCT product_id) AS product_count
FROM sales
GROUP BY pricing_tier;
-- Insight: Helps product managers understand catalog price distributions and portfolio skew.

-- Q28: Show total discount amounts given per category, flagging categories exceeding $10,000 total discount.
-- SQL:
SELECT 
    p.category,
    ROUND(SUM(s.sales * s.discount)::numeric, 2) AS discount_allocated,
    CASE 
        WHEN SUM(s.sales * s.discount) > 10000 THEN 'Review Discounts (Excessive)'
        ELSE 'Approved Budget Limit'
    END AS discount_audit_status
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category;
-- Insight: Internal audit tool to flag categories where discounting has exceeded acceptable allowances.

-- Q29: Categorize customers based on total transaction count.
-- SQL:
SELECT 
    customer_id,
    COUNT(DISTINCT order_id) AS total_orders,
    CASE 
        WHEN COUNT(DISTINCT order_id) >= 10 THEN 'VIP Loyal'
        WHEN COUNT(DISTINCT order_id) BETWEEN 5 AND 9 THEN 'Regular Buyer'
        ELSE 'One-time/Occasional'
    END AS customer_tier
FROM sales
GROUP BY customer_id
LIMIT 10;
-- Insight: Direct customer segmentation feed for target email drip campaigns.

-- Q30: Label profit margins per transaction, counting volume of negative margin transactions.
-- SQL:
SELECT 
    p.category,
    SUM(CASE WHEN s.profit < 0 THEN 1 ELSE 0 END) AS unprofitable_sales_count,
    COUNT(s.order_line) AS total_sales_count,
    ROUND((SUM(CASE WHEN s.profit < 0 THEN 1 ELSE 0 END)::numeric / COUNT(s.order_line)) * 100, 2) AS loss_rate_percent
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category;
-- Insight: Evaluates transactional failure rates. Highlights which categories have pricing flaws causing frequent net losses.

-- ------------------------------------------------------------------------------
-- 🎯 PART 4: WINDOW FUNCTIONS & RANKING (QUERIES 31-40)
-- ------------------------------------------------------------------------------

-- Q31: Rank products by revenue inside their respective categories.
-- SQL:
WITH product_sales AS (
    SELECT 
        p.category,
        p.product_name,
        SUM(s.sales) AS total_revenue
    FROM sales s
    JOIN products p ON s.product_id = p.product_id
    GROUP BY p.category, p.product_name
)
SELECT 
    category,
    product_name,
    ROUND(total_revenue::numeric, 2) AS total_revenue,
    DENSE_RANK() OVER(PARTITION BY category ORDER BY total_revenue DESC) AS rank_in_category
FROM product_sales
QUALIFY DENSE_RANK() OVER(PARTITION BY category ORDER BY total_revenue DESC) <= 3;
-- Note: PostgreSQL supports QUALIFY or filtering with subqueries.
-- Insight: Identifies the top 3 core revenue contributors per product category.

-- Q32: Calculate the running total of sales for each month in 2017.
-- SQL:
WITH monthly_sales AS (
    SELECT 
        DATE_TRUNC('month', order_date::date) AS sales_month,
        SUM(sales) AS revenue
    FROM sales
    WHERE EXTRACT(YEAR FROM order_date::date) = 2017
    GROUP BY sales_month
)
SELECT 
    sales_month,
    ROUND(revenue::numeric, 2) AS monthly_revenue,
    ROUND(SUM(revenue) OVER(ORDER BY sales_month)::numeric, 2) AS running_total_ytd
FROM monthly_sales;
-- Insight: Essential corporate reporting visual showing progress toward year-end targets.

-- Q33: Find the difference in sales between each month and the prior month (MoM Growth).
-- SQL:
WITH monthly_sales AS (
    SELECT 
        DATE_TRUNC('month', order_date::date) AS sales_month,
        SUM(sales) AS revenue
    FROM sales
    GROUP BY sales_month
)
SELECT 
    sales_month,
    ROUND(revenue::numeric, 2) AS current_sales,
    ROUND(LAG(revenue, 1) OVER (ORDER BY sales_month)::numeric, 2) AS prior_month_sales,
    ROUND((revenue - LAG(revenue, 1) OVER (ORDER BY sales_month))::numeric, 2) AS mom_difference,
    ROUND(((revenue - LAG(revenue, 1) OVER (ORDER BY sales_month)) / LAG(revenue, 1) OVER (ORDER BY sales_month) * 100)::numeric, 2) AS mom_growth_percent
FROM monthly_sales;
-- Insight: Measures sales momentum. Spotting sharp drops allows teams to adjust pricing or launch promotions.

-- Q34: Rank customers in each region by their total profit contribution.
-- SQL:
WITH customer_regional_profit AS (
    SELECT 
        c.region,
        c.customer_id,
        c.customer_name,
        SUM(s.profit) AS total_profit
    FROM sales s
    JOIN customers c ON s.customer_id = c.customer_id
    GROUP BY c.region, c.customer_id, c.customer_name
)
SELECT 
    region,
    customer_name,
    ROUND(total_profit::numeric, 2) AS total_profit,
    ROW_NUMBER() OVER(PARTITION BY region ORDER BY total_profit DESC) AS profit_rank
FROM customer_regional_profit
ORDER BY region, profit_rank;
-- Insight: Identifies primary VIP customers per regional workspace for local sales reps to cultivate.

-- Q35: Calculate a 3-month moving average of sales.
-- SQL:
WITH monthly_sales AS (
    SELECT 
        DATE_TRUNC('month', order_date::date) AS sales_month,
        SUM(sales) AS revenue
    FROM sales
    GROUP BY sales_month
)
SELECT 
    sales_month,
    ROUND(revenue::numeric, 2) AS revenue,
    ROUND(AVG(revenue) OVER(
        ORDER BY sales_month 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    )::numeric, 2) AS rolling_3_month_avg
FROM monthly_sales;
-- Insight: Smooths out seasonal fluctuations (like holiday sales spikes) to show the underlying business trajectory.

-- Q36: Find the first and last purchase date for each customer.
-- SQL:
SELECT 
    customer_id,
    MIN(order_date) OVER(PARTITION BY customer_id) AS first_order_date,
    MAX(order_date) OVER(PARTITION BY customer_id) AS last_order_date
FROM sales
LIMIT 5;
-- Insight: Essential foundation for loyalty segment analysis and churn calculations.

-- Q37: Assign percentile rankings to products based on total quantity sold.
-- SQL:
WITH product_qtys AS (
    SELECT 
        product_id,
        SUM(quantity) AS total_qty
    FROM sales
    GROUP BY product_id
)
SELECT 
    product_id,
    total_qty,
    NTILE(100) OVER(ORDER BY total_qty DESC) AS sales_percentile
FROM product_qtys;
-- Insight: Identifies the top 1% (highly viral) vs. bottom 10% (underperforming) products.

-- Q38: Calculate lead and lag days between orders for a specific customer (e.g. CG-12520).
-- SQL:
SELECT 
    order_id,
    order_date,
    LAG(order_date, 1) OVER(ORDER BY order_date) AS prior_order_date,
    (order_date::date - LAG(order_date, 1) OVER(ORDER BY order_date)::date) AS days_between_purchases
FROM sales
WHERE customer_id = 'CG-12520'
ORDER BY order_date;
-- Insight: Tracks purchase frequency at the individual customer level.

-- Q39: Show the percentage contribution of each sub-category's sales to its main category's sales.
-- SQL:
WITH sub_cat_sales AS (
    SELECT 
        p.category,
        p.sub_category,
        SUM(s.sales) AS sub_sales
    FROM sales s
    JOIN products p ON s.product_id = p.product_id
    GROUP BY p.category, p.sub_category
)
SELECT 
    category,
    sub_category,
    ROUND(sub_sales::numeric, 2) AS sub_sales,
    ROUND((sub_sales / SUM(sub_sales) OVER(PARTITION BY category) * 100)::numeric, 2) AS percent_contribution_to_category
FROM sub_cat_sales
ORDER BY category, percent_contribution_to_category DESC;
-- Insight: Helps product managers allocate shelf space and marketing budget to high-performing subcategories.

-- Q40: Identify the top 10% of customers by profit contribution globally.
-- SQL:
WITH customer_profits AS (
    SELECT 
        customer_id,
        SUM(profit) AS total_profit
    FROM sales
    GROUP BY customer_id
),
ranked_customers AS (
    SELECT 
        customer_id,
        total_profit,
        PERCENT_RANK() OVER(ORDER BY total_profit DESC) AS pct_rank
    FROM customer_profits
)
SELECT 
    customer_id,
    ROUND(total_profit::numeric, 2) AS net_profit
FROM ranked_customers
WHERE pct_rank <= 0.10
ORDER BY net_profit DESC;
-- Insight: High-level VIP customer listing. These top 10% customers generate the majority of profit.

-- ------------------------------------------------------------------------------
-- 🎯 PART 5: ADVANCED CTEs, COHORT, & RETENTION (QUERIES 41-50)
-- ------------------------------------------------------------------------------

-- Q41: Customer Cohort Grouping - Find month of first purchase for each customer.
-- SQL:
WITH cohort_creation AS (
    SELECT 
        customer_id,
        MIN(DATE_TRUNC('month', order_date::date)) AS cohort_month
    FROM sales
    GROUP BY customer_id
)
SELECT 
    cohort_month,
    COUNT(DISTINCT customer_id) AS new_customers_acquired
FROM cohort_creation
GROUP BY cohort_month
ORDER BY cohort_month;
-- Insight: Tracks acquisition velocity. Shows if new customer sign-ups are growing over time.

-- Q42: Calculate Repeat Purchase Rate within 30 Days.
-- SQL:
WITH first_purchases AS (
    SELECT customer_id, MIN(order_date::date) AS first_date
    FROM sales
    GROUP BY customer_id
),
subsequent_purchases AS (
    SELECT s.customer_id, s.order_date::date AS next_date
    FROM sales s
    JOIN first_purchases fp ON s.customer_id = fp.customer_id
    WHERE s.order_date::date > fp.first_date
)
SELECT 
    COUNT(DISTINCT fp.customer_id) AS total_new_customers,
    COUNT(DISTINCT sp.customer_id) AS returned_in_30_days,
    ROUND((COUNT(DISTINCT sp.customer_id)::numeric / COUNT(DISTINCT fp.customer_id) * 100), 2) AS return_rate_30d
FROM first_purchases fp
LEFT JOIN subsequent_purchases sp ON fp.customer_id = sp.customer_id 
    AND sp.next_date <= fp.first_date + INTERVAL '30 days';
-- Insight: Core product-market fit metric. High repeat rates prove product value and customer satisfaction.

-- Q43: Subscription Retention Rate Month-over-Month (Cohort Retention Matrix style).
-- SQL:
WITH customer_activity AS (
    SELECT DISTINCT
        customer_id,
        DATE_TRUNC('month', order_date::date) AS activity_month
    FROM sales
),
cohort_start AS (
    SELECT 
        customer_id,
        MIN(activity_month) AS cohort_month
    FROM customer_activity
    GROUP BY customer_id
)
SELECT 
    c.cohort_month,
    ROUND(EXTRACT(epoch FROM (a.activity_month - c.cohort_month)) / (30*24*60*60)) AS month_number,
    COUNT(DISTINCT a.customer_id) AS active_customers
FROM customer_activity a
JOIN cohort_start c ON a.customer_id = c.customer_id
GROUP BY c.cohort_month, month_number
ORDER BY c.cohort_month, month_number;
-- Insight: Creates the classic retention heatmap feed. Visualizes customer lifespans across cohort ages.

-- Q44: Find the total revenue from "Returning Customers" vs "New Customers" per year.
-- SQL:
WITH customer_orders AS (
    SELECT 
        customer_id,
        order_id,
        sales,
        EXTRACT(YEAR FROM order_date::date) AS sales_year,
        MIN(EXTRACT(YEAR FROM order_date::date)) OVER (PARTITION BY customer_id) AS acquisition_year
    FROM sales
)
SELECT 
    sales_year,
    ROUND(SUM(CASE WHEN sales_year = acquisition_year THEN sales ELSE 0 END)::numeric, 2) AS new_customer_revenue,
    ROUND(SUM(CASE WHEN sales_year > acquisition_year THEN sales ELSE 0 END)::numeric, 2) AS returning_customer_revenue
FROM customer_orders
GROUP BY sales_year
ORDER BY sales_year;
-- Insight: Evaluates CAC (Customer Acquisition Cost) vs LTV (Lifetime Value). If returning revenue increases, profit margins improve.

-- Q45: Identify the "Most Valued Churn Risks" (No purchases in the last 180 days but historic spending > $5,000).
-- SQL:
WITH customer_profile AS (
    SELECT 
        customer_id,
        MAX(order_date::date) AS last_order_date,
        SUM(sales) AS lifetime_sales
    FROM sales
    GROUP BY customer_id
)
SELECT 
    customer_id,
    last_order_date,
    ROUND(lifetime_sales::numeric, 2) AS lifetime_sales,
    ('2018-01-01'::date - last_order_date) AS days_since_last_purchase -- Assuming snapshot reference date
FROM customer_profile
WHERE ('2018-01-01'::date - last_order_date) > 180 
  AND lifetime_sales > 5000
ORDER BY lifetime_sales DESC;
-- Insight: High-priority outreach list. These were heavy spenders who have gone inactive.

-- Q46: Calculate Year-over-Year (YoY) Growth at the Segment level.
-- SQL:
WITH annual_segment_sales AS (
    SELECT 
        c.segment,
        EXTRACT(YEAR FROM s.order_date::date) AS sales_year,
        SUM(s.sales) AS revenue
    FROM sales s
    JOIN customers c ON s.customer_id = c.customer_id
    GROUP BY c.segment, sales_year
)
SELECT 
    curr.segment,
    curr.sales_year,
    ROUND(curr.revenue::numeric, 2) AS current_revenue,
    ROUND(prev.revenue::numeric, 2) AS prior_revenue,
    ROUND(((curr.revenue - prev.revenue) / prev.revenue * 100)::numeric, 2) AS yoy_growth_percent
FROM annual_segment_sales curr
LEFT JOIN annual_segment_sales prev 
    ON curr.segment = prev.segment AND curr.sales_year = prev.sales_year + 1
ORDER BY curr.segment, curr.sales_year;
-- Insight: Identifies market segment expansion rates. Useful for aligning corporate strategy with high-growth segments.

-- Q47: Find products that are bought together (Market Basket Analysis / Self-Join).
-- SQL:
SELECT 
    s1.product_id AS product_a,
    s2.product_id AS product_b,
    COUNT(DISTINCT s1.order_id) AS co_purchase_count
FROM sales s1
JOIN sales s2 ON s1.order_id = s2.order_id AND s1.product_id < s2.product_id
GROUP BY s1.product_id, s2.product_id
ORDER BY co_purchase_count DESC
LIMIT 5;
-- Insight: Identifies cross-selling bundles. Products frequently bought together can be placed in product bundles.

-- Q48: Find the Top 3 orders by revenue for each customer segment.
-- SQL:
WITH customer_orders AS (
    SELECT 
        c.segment,
        s.order_id,
        SUM(s.sales) AS order_value
    FROM sales s
    JOIN customers c ON s.customer_id = c.customer_id
    GROUP BY c.segment, s.order_id
),
ranked_orders AS (
    SELECT 
        segment,
        order_id,
        order_value,
        DENSE_RANK() OVER(PARTITION BY segment ORDER BY order_value DESC) AS rank
    FROM customer_orders
)
SELECT 
    segment,
    order_id,
    ROUND(order_value::numeric, 2) AS order_value
FROM ranked_orders
WHERE rank <= 3;
-- Insight: Showcases heavy-ticket order transactions inside segments.

-- Q49: Calculate customer churn rate for a subscription dataset.
-- (Assumes a subscription table schema: customer_id, signup_date, end_date)
-- SQL:
WITH monthly_status AS (
    SELECT 
        customer_id,
        DATE_TRUNC('month', order_date::date) AS active_month
    FROM sales
),
customer_churn AS (
    SELECT 
        active_month,
        COUNT(DISTINCT customer_id) AS active_this_month,
        LEAD(COUNT(DISTINCT customer_id)) OVER (ORDER BY active_month) AS active_next_month
    FROM monthly_status
    GROUP BY active_month
)
SELECT 
    active_month,
    active_this_month,
    ROUND(((active_this_month - COALESCE(active_next_month, active_this_month))::numeric / active_this_month * 100), 2) AS monthly_churn_rate_percent
FROM customer_churn;
-- Insight: Evaluates customer attrition velocity.

-- Q50: Find the total value of sales returned (Sales rows where profit is deeply negative and quantity is negative).
-- SQL:
SELECT 
    EXTRACT(YEAR FROM order_date::date) AS sales_year,
    ROUND(SUM(CASE WHEN profit < 0 AND discount > 0.5 THEN sales ELSE 0 END)::numeric, 2) AS total_returned_sales_value,
    ROUND((SUM(CASE WHEN profit < 0 AND discount > 0.5 THEN sales ELSE 0 END) / SUM(sales) * 100)::numeric, 2) AS return_rate_percent
FROM sales
GROUP BY sales_year;
-- Insight: Quantifies the overall loss rate due to heavy discounts and returns.
